{
    "name":"Sistem Informasi Akademik V1.0",
    "version":"1.0",
    "depends": ["base","board"],
    "author":"Budi Irawan",
    "category":"Education",
    "website":"https://bootcamp.vitraining.com",
    "description": """Aplikasi Sistem Informasi Akademik""",
    "data":[
        "security/groups.xml",
        "security/ir.model.access.csv",
        "menu.xml",
        "course.xml",
        "session.xml",
        "attendee.xml",
        "partner.xml",
        "wizard/create_attendee.xml",
        "reports/session.xml",
        "dashboard.xml"
    ],
    "installable":True,
    "auto_install":False,
    "application":True,
    "license": "LGPL-3",
}